- id: '1591814013567'
  alias: Away
  description: ''
  trigger:
  - entity_id: person.jason
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - type: turn_off
    device_id: 244fff1545e79f3accba5ef1c84baf8e
    entity_id: switch.lava_lamp
    domain: switch
  - type: turn_off
    device_id: 352f0f0f52f6fd204ecfd729f6122638
    entity_id: switch.salt_lamp
    domain: switch
  - type: turn_off
    device_id: 6707a00f34b32dc52390bd1bbeaf75c0
    entity_id: switch.bong_lamp
    domain: switch
  - type: turn_off
    device_id: 29515b628ba07c72dd61d6899a0f796a
    entity_id: switch.italian_vase_lamp
    domain: switch
  - type: turn_off
    device_id: 4111f19842bc25c19254dbb5b18de7ae
    entity_id: light.rock_and_rye_light
    domain: light
  - type: turn_off
    device_id: 4111f19842bc25c19254dbb5b18de7ae
    entity_id: light.pocket_watch_light
    domain: light
  mode: single
- id: '1591915766628'
  alias: Off 10PM
  description: Turn lights off at 10PM
  trigger:
  - at: '23:00:00'
    platform: time
  condition: []
  action:
  - type: turn_off
    device_id: c14e4472491daf9e3e731750d4601fe1
    entity_id: light.kitchen_cabinet_lightstrip
    domain: light
  mode: single
- id: '1591917817012'
  alias: Wake-up
  description: Turn on lights at first alarm
  trigger:
  - at: 05:00:00
    platform: time
  condition: []
  action:
  - scene: scene.kitchen_lightstrip_morning
  - scene: scene.nick_nack_random
  mode: single
- id: '1592782675006'
  alias: Morning 7AM
  description: Stuff to do at 7AM
  trigger:
  - at: 07:00
    platform: time
  condition: []
  action:
  - device_id: c8ef6a20cdf54e509f97e29680b7e215
    domain: switch
    entity_id: switch.bong_lamp
    type: turn_off
  - scene: scene.bong_lamp_led_random
  - device_id: a7bbbb68a5ed47f48915c4f45fffeaf9
    domain: light
    entity_id: light.rock_and_rye_light
    type: turn_off
  - device_id: a7bbbb68a5ed47f48915c4f45fffeaf9
    domain: light
    entity_id: light.pocket_watch_light
    type: turn_off
  mode: single
- id: '1593448013742'
  alias: Sunset
  description: Lights to turn on at sunset
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - scene: scene.nick_nack_random
  - scene: scene.bong_lamp_led_random
  - scene: scene.kitchen_lightstrip_morning
  - type: turn_on
    device_id: 244fff1545e79f3accba5ef1c84baf8e
    entity_id: switch.lava_lamp
    domain: switch
  - type: turn_on
    device_id: 352f0f0f52f6fd204ecfd729f6122638
    entity_id: switch.salt_lamp
    domain: switch
  mode: single
- id: '1605646082723'
  alias: Arrive Home
  description: Arrive home
  trigger:
  - platform: zone
    entity_id: person.jason
    zone: zone.home
    event: enter
  condition: []
  action:
  - type: turn_on
    device_id: 6707a00f34b32dc52390bd1bbeaf75c0
    entity_id: switch.bong_lamp
    domain: switch
  - type: turn_on
    device_id: 29515b628ba07c72dd61d6899a0f796a
    entity_id: switch.italian_vase_lamp
    domain: switch
  - scene: scene.kitchen_lightstrip_morning
  - scene: scene.nick_nack_random
  - type: turn_on
    device_id: 685d180a1eb0482103ac5cb9a6174ce8
    entity_id: light.floor_lamp
    domain: light
    brightness_pct: 100
  mode: single
- id: '1605717382656'
  alias: Hue Scene Test
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: Entertainment Center
      scene_name: Zany
  mode: single
