- id: '1591814013567'
  alias: Away
  description: ''
  trigger:
  - entity_id: person.jason
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - type: turn_off
    device_id: 8aa948545f49302d431832d5b63d9a7f
    entity_id: switch.lg_webos_tv_uk6090pua_lg_tv
    domain: switch
  - service: homeassistant.turn_off
    data:
      entity_id: group.bedroom_nightstand
    entity_id: group.bedroom_nightstand
  - service: homeassistant.turn_off
    data:
      entity_id: group.nick_nacks
    entity_id: group.nick_nacks
  - service: homeassistant.turn_off
    data:
      entity_id: group.entertainment_center_2
    entity_id: group.entertainment_center_2
  - type: turn_off
    device_id: c14e4472491daf9e3e731750d4601fe1
    entity_id: light.kitchen_cabinet_lightstrip
    domain: light
  mode: single
- id: '1591915766628'
  alias: Off 11PM
  description: Turn lights off at 11PM
  trigger:
  - at: '23:00:00'
    platform: time
  condition: []
  action:
  - type: turn_off
    device_id: c14e4472491daf9e3e731750d4601fe1
    entity_id: light.kitchen_cabinet_lightstrip
    domain: light
  - service: homeassistant.turn_off
    data:
      entity_id: group.nick_nacks
    entity_id: group.nick_nacks
  mode: single
- id: '1591917817012'
  alias: Wake-up
  description: Turn on lights at first alarm
  trigger:
  - at: 05:00:00
    platform: time
  condition:
  - condition: zone
    entity_id: person.jason
    zone: zone.home
  action:
  - scene: scene.kitchen_lightstrip_morning
  - scene: scene.nick_nack_random
  mode: single
- id: '1592782675006'
  alias: Morning 7AM
  description: Stuff to do at 7AM
  trigger:
  - at: 07:00
    platform: time
  condition:
  - condition: zone
    entity_id: person.jason
    zone: zone.home
  action:
  - scene: scene.bong_lamp_led_random
  - service: light.turn_on
    data:
      transition: 600
      brightness: 255
    entity_id: light.living_room_overhead
  - service: light.turn_on
    data:
      transition: 600
      brightness: 255
    entity_id: light.bedroom_overhead
  - service: light.turn_on
    data:
      transition: 600
      brightness: 255
    entity_id: light.office
  mode: single
- id: '1593448013742'
  alias: Sunset
  description: Lights to turn on at sunset
  trigger:
  - event: sunset
    platform: sun
  condition:
  - condition: zone
    entity_id: person.jason
    zone: zone.home
  action:
  - scene: scene.nick_nack_random
  - scene: scene.bong_lamp_led_random
  - scene: scene.kitchen_lightstrip_morning
  - service: homeassistant.turn_on
    data:
      entity_id: group.entertainment_center_2
    entity_id: group.entertainment_center_2
  - service: script.entertainment_center_zany
    data: {}
  mode: single
- id: '1605646082723'
  alias: Arrive Home
  description: Arrive home
  trigger:
  - platform: zone
    entity_id: person.jason
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: group.bedroom_nightstand
    entity_id: group.bedroom_nightstand
  - service: script.living_room_bright
    data: {}
  - scene: scene.kitchen_lightstrip_morning
  - scene: scene.nick_nack_random
  - scene: scene.kitchen_prep
  mode: single
- id: '1606329407790'
  alias: Away at night
  description: If I am away, turn on lights at sunset
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: person.jason
    state: away
  action:
  - type: turn_on
    device_id: 685d180a1eb0482103ac5cb9a6174ce8
    entity_id: light.floor_lamp
    domain: light
    brightness_pct: 50
  mode: single
- id: '1607373949770'
  alias: Add Torrent
  description: Add torrent from text file
  trigger:
  - platform: state
    entity_id: input_text.torrent_url
  condition: []
  action:
  - service: transmission.add_torrent
    data:
      value: '{{ states(''input_text.torrent_url'') }}'
  mode: single
