# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named themes
homeassistant:
  name: Chez Herm
  latitude: 36.972044
  longitude: -122.028718
  elevation: 36
  unit_system: imperial
  time_zone: America/Los_Angeles
  external_url: "https://chezherm.duckdns.org:8123"
  internal_url: "https://homeassistant:8123"
  #whitelist_external_dirs:
  #  - /usr/var/dumping-ground
  #  - /tmp

#HACS debug
logger:
  default: info
  logs:
    custom_components.hacs: debug
    hacs: debug
    queueman: debug
    AIOGitHubAPI: debug
#Configure device trackers
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.86.0/24
# Configure http for ssl certificate
http:
  base_url: chezherm.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Enable Wake ON Lan
wake_on_lan:

# LG WebOS TV
webostv:
  host: 192.168.86.39
  name: LG TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: a8:23:fe:56:99:12
      broadcast_address: 192.168.86.39
  customize:
    sources:
      - YouTube TV
      - Live TV
      - Channel Plus
      - Netflix
      - Amazon Prime Video
      - YouTube
      - Emby
      - Plex
      - HDMI 1
      - HDMI 2
      - HDMI 3

media_player:

# Sensors
# Example configuration.yaml entry
sensor:
  - platform: lastfm
    api_key: ec90320d2a138cbb909906452635f5a2
    users:
      - Herm71
  - platform: flunearyou
  - platform: noaa_tides
    station_id: 9413745
    time_zone: lst_ldt
    unit_system: english
  - platform: google_wifi
    host: onhub.here
    name: Google google_wifi
    monitored_conditions:
      - current_version
      - new_version
      - uptime
      - last_restart
      - local_ip
      - status
  - platform: template
    sensors:
      nextsunrise:
        entity_id: sun.sun
        friendly_name: "Next Sunrise"
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-up
      nextsunset:
        entity_id: sun.sun
        friendly_name: "Next Sunset"
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-down
  - platform: moon
  - platform: season
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
      - "beat"
  - platform: template
    sensors:
      weekday:
        value_template: "{{ now().strftime('%a') }}"
        entity_id: sensor.date
        friendly_name: "Day of Week"
      newdate:
        value_template: "{{ now().strftime('%m %d %y') }}"
        entity_id: sensor.date
        friendly_name: "Today's Date"
  - platform: template
    sensors:
      lastfm_currenttrack:
        friendly_name: "Current Track"
        value_template: >-
          {% if states.sensor.herm71 %}
          {{states.sensor.herm71.state}}
          {%endif%}
        unique_id: lastfm.currenttrack
      lastfm_lasttrack:
        friendly_name: "Last Track"
        value_template: >-
          {% if states.sensor.herm71 %}
          {{state_attr('sensor.herm71','last_played')}}
          {%endif%}
        unique_id: lastfm.lasttrack
      lastfm_toptrack:
        friendly_name: "Top Track"
        value_template: >-
          {% if states.sensor.herm71 %}
          {{state_attr('sensor.herm71','top_played')}}
          {%endif%}
        unique_id: lastfm.total
      lastfm_total:
        friendly_name: "Total Tracks"
        value_template: >-
          {% if states.sensor.herm71 %}
          {{state_attr('sensor.herm71','play_count')}}
          {%endif%}
        unique_id: lastfm.toptrack
  - platform: template
    sensors:
      plexmusic_track:
        friendly_name: "Track"
        value_template: >-
          {% if states.media_player.plex_plex_cast_chromecast %}
          {{state_attr('media_player.plex_plex_cast_chromecast','media_title')}}
          {%endif%}
        unique_id: plexmusic.track
      plexmusic_artist:
        friendly_name: "Artist"
        value_template: >-
          {% if states.media_player.plex_plex_cast_chromecast %}
          {{state_attr('media_player.plex_plex_cast_chromecast','media_artist')}}
          {%endif%}
        unique_id: plexmusic.artist
      plexmusic_album:
        friendly_name: "Album"
        value_template: >-
          {% if states.media_player.plex_plex_cast_chromecast %}
          {{state_attr('media_player.plex_plex_cast_chromecast','media_album_name')}}
          {%endif%}
        unique_id: plexmusic.album
      plexmusic_albumart:
        friendly_name: "Album Art"
        value_template: >-
          {% if states.media_player.plex_plex_cast_chromecast %}
          {{state_attr('media_player.plex_plex_cast_chromecast','entity_picture')}}
          {%endif%}
        unique_id: plexmusic.albumart

# Voice commands -- conversation
conversation:
  intents:
    BongLampOff:
      - "Turn the Bong Lamp off"
      - "Turn off the Bong Lamp"
    BongLampOn:
      - "Turn the Bong Lamp on"
      - "Turn on the Bong Lamp"
    VaseLampOff:
      - "Turn the Vase Lamp off"
      - "Turn off the Vase Lamp"
    VaseLampOn:
      - "Turn the Vase Lamp on"
      - "Turn on the Vase Lamp"
    KitchenLightStripOff:
      - "Turn the Kitchen Cabinet Lightstrip off"
      - "Turn off the Kitchen Cabinet Lightstrip"
    KitchenLightStripOn:
      - "Turn the Kitchen Cabinet Lightstrip on"
      - "Turn on the Kitchen Cabinet Lightstrip"
intent_script:
  BongLampOff:
    speech:
      text: Turning the Bong Lamp off
    action:
      service: switch.turn_off
      data:
        entity_id: switch.bong_lamp
  BongLampOn:
    speech:
      text: Turning the Bong Lamp on
    action:
      service: switch.turn_on
      data:
        entity_id: switch.bong_lamp
  VaseLampOff:
    speech:
      text: Turning the Vase Lamp off
    action:
      service: switch.turn_off
      data:
        entity_id: switch.italian_vase_lamp
  VaseLampOn:
    speech:
      text: Turning the Vase Lamp on
    action:
      service: switch.turn_on
      data:
        entity_id: switch.italian_vase_lamp
  KitchenLightStripOff:
    speech:
      text: Turning the Kitchen Cabinet Lightstrip off
    action:
      service: switch.turn_off
      data:
        entity_id: switch.italian_vase_lamp
  KitchenLightStripOn:
    speech:
      text: Turning the Kitchen Cabinet Lightstrip on
    action:
      service: switch.turn_on
      data:
        entity_id: switch.italian_vase_lamp
