# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: https://chezherm.duckdns.org:8123
    service_name: google_say

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
device_tracker: !include device_trackers.yaml
frontend:
  themes: !include_dir_merge_named themes
homeassistant:
  name: Chez Herm
  latitude: 36.972044
  longitude: -122.028718
  elevation: 36
  unit_system: imperial
  time_zone: America/Los_Angeles
  external_url: "https://chezherm.duckdns.org:8123"
  internal_url: "https://homeassistant:8123"
  #whitelist_external_dirs:
  #  - /usr/var/dumping-ground
  #  - /tmp

#HACS debug
logger:
  default: info
  logs:
    custom_components.hacs: debug
    hacs: debug
    queueman: debug
    AIOGitHubAPI: debug
# Configure http for ssl certificate
http:
  base_url: chezherm.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Enable Wake ON Lan
wake_on_lan:

# LG WebOS TV
webostv:
  host: 192.168.86.39
  name: LG TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: a8:23:fe:56:99:12
      broadcast_address: 192.168.86.39
  customize:
    sources:
      - YouTube TV
      - Live TV
      - Channel Plus
      - Netflix
      - Amazon Prime Video
      - YouTube
      - Emby
      - Plex
      - LG Content Store
      - HDMI 1
      - HDMI 2
      - HDMI 3

media_player:

#MQTT Broker
mqtt:
  broker: 192.168.86.86
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_user
  password: !secret mqtt_user_pass

# Voice commands -- conversation
conversation:
  intents:
    BongLampOff:
      - "Turn the Bong Lamp off"
      - "Turn off the Bong Lamp"
    BongLampOn:
      - "Turn the Bong Lamp on"
      - "Turn on the Bong Lamp"
    VaseLampOff:
      - "Turn the Italian Lamp off"
      - "Turn off the Italian Lamp"
    VaseLampOn:
      - "Turn the Italian Lamp on"
      - "Turn on the Italian Lamp"
    KitchenLightStripOff:
      - "Turn the Kitchen Cabinet Lightstrip off"
      - "Turn off the Kitchen Cabinet Lightstrip"
    KitchenLightStripOn:
      - "Turn the Kitchen Cabinet Lightstrip on"
      - "Turn on the Kitchen Cabinet Lightstrip"
    KitchenLightStripPrep:
      - "Set Kitchen Cabinet Lightstrip to prep"
      - "Set the Kitchen Cabinet Lightstrip prep scene"
    KitchenLightStripMorning:
      - "Set Kitchen Cabinet Lightstrip to morning"
      - "Set the Kitchen Cabinet Lightstrip morning scene"
    KitchenLightStripRandom:
      - "Set Kitchen Cabinet Lightstrip to random"
      - "Set the Kitchen Cabinet Lightstrip random scene"
intent_script:
  BongLampOff:
    speech:
      text: Turning the Bong Lamp off
    action:
      service: switch.turn_off
      data:
        entity_id: switch.bong_lamp
  BongLampOn:
    speech:
      text: Turning the Bong Lamp on
    action:
      service: switch.turn_on
      data:
        entity_id: switch.bong_lamp
  VaseLampOff:
    speech:
      text: Turning the Italian Lamp off
    action:
      service: switch.turn_off
      data:
        entity_id: switch.italian_vase_lamp
  VaseLampOn:
    speech:
      text: Turning the Italian Lamp on
    action:
      service: switch.turn_on
      data:
        entity_id: switch.italian_vase_lamp
  KitchenLightStripOff:
    speech:
      text: Turning the Kitchen Cabinet Lightstrip off
    action:
      service: light.turn_off
      data:
        entity_id: light.kitchen_cabinet_lightstrip
  KitchenLightStripOn:
    speech:
      text: Turning the Kitchen Cabinet Lightstrip on
    action:
      service: light.turn_on
      data:
        entity_id: light.kitchen_cabinet_lightstrip
  KitchenLightStripPrep:
    speech:
      text: Setting the kitchen lightstrip scene to Prep
    action:
      service: scene.turn_on
      data:
        entity_id: scene.kitchen_prep
  KitchenLightStripMorning:
    speech:
      text: Setting the kitchen lightstrip scene to Morning
    action:
      service: scene.turn_on
      data:
        entity_id: scene.kitchen_lightstrip_morning
  KitchenLightStripRandom:
    speech:
      text: Setting the kitchen lightstrip scene to Random
    action:
      service: scene.turn_on
      data:
        entity_id: scene.kitchen_lightstrip_random

# Devices -- MQTT Platform
switch:
  - platform: mqtt
    unique_id: bong_lamp_switch
    device:
      identifiers: switch.bong_lamp
      name: "Bong Lamp"
    command_topic: "home/bedroom/bongLamp/set"
    state_topic: "home/bedroom/bongLamp"
    availability:
      - topic: "home/bedroom/bongLamp/available"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
